import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { DockDemo } from "@/components/dock";
import "./globals.css";
import "../util/css/satoshi.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col h-screen p-4">
            {children}
            <DockDemo />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
